namespace Librariann.Models.Entities.Enums;

public enum ReadingProfileKind
{
    /// <summary>
    /// Generate by Librariann when registering a user, this is your default profile
    /// </summary>
    Default,
    /// <summary>
    /// Created by the user in the UI or via the API
    /// </summary>
    User,
    /// <summary>
    /// Automatically generated by Librariann to track changes made in the readers. Can be converted to a User Reading Profile.
    /// </summary>
    Implicit
}
